# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
email: your-email@domain.com
markdown: kramdown
description: > # this means to ignore newlines until "baseurl:"
   Castle Farm is a family run arable farm with a flock of sheep 
   outside the market town of Knaresborough. The farm also hosts 
   a small number of weddings.

baseurl: "" # the subpath of your site, e.g. /blog

url: "http://castle-farm.net" # the base hostname & protocol for your site

twitter_username: jekyllrb
github_username:  jekyll

colours:
  A: "#000000"

prose:
  rooturl: 'content'
  siteurl: "http://castle-farm.net"
  media: "images"
  ignore: [INFO.md]
